# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# This is used for ASH security scanning
include:
  - component: code.aws.dev/proserve/automated-security-helper/automated-security-helper/ash@~latest

# Any publicly available python image
image: public.ecr.aws/docker/library/python:3.13-bookworm

stages:
  - developer_tests
  - test # Need this name specifically for ASH scanning

developer_tests:
  stage: developer_tests
  rules:
    - when: always  # Run on all branches

  before_script:
      - python --version
      - apt-get update -y
      - apt-get install make -y
      - pip install ruff

  script:
      - make lint-cicd
